spring.application.name=banking-system

spring.datasource.url=jdbc:postgresql://localhost:5432/banking-system-java
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970